[project]
name = "finalproject_Ovsyannikov_Sergey_M25-555"
version = "0.1.0"
description = ""
authors = [
    {name = "Sergey Ovsyannikov",email = "s.ovsyannikov@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.32.5,<3.0.0)"
]

[tool.poetry]
packages = [
     { include = "valutatrade_hub", from = "." },
 ]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
project = "main:main"